//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Authors")
export class AuthorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Name: string;

@Column({nullable: true})
Books: string;

@Column({nullable: true})
Id: string;


}
