//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Author")
export class AuthorEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Name: string;

@Column({nullable: true})
Biography: string;

@Column({nullable: true})
Nationality: string;

@Column({nullable: true})
Id: string;


}
