//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Book")
export class BookEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Title: string;

@Column({nullable: true})
Releasedate: string;

@Column({nullable: true})
Description: string;

@Column({nullable: true})
Id: string;


}
