//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Genres")
export class GenresEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Category: string;

@Column({nullable: true})
Id: string;


}
