//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Publisher")
export class PublisherEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Name: string;

@Column({nullable: true})
Location: string;

@Column({nullable: true})
Contactinformation: string;

@Column({nullable: true})
Id: string;


}
